const sampleProperties = [

    {
        title: "The Heritage Villa",
        description: "Classic architecture with a private garden and pool.",
        image: { url: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?q=80&w=1000&auto=format&fit=crop" },
        price: 250000,
        deposit: 500000,
        location: "Civil Lines",
        city: "Delhi",
        country: "India",
        propertyType: "Villa",
        bhk: "4 BHK",
        furnishing: "Unfurnished",
        status: "approved",
        amenities: ["Swimming Pool", "Power Backup"]
    },
    {
        title: "Cozy Studio PG",
        description: "Affordable and managed stay for students.",
        image: { url: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?q=80&w=1000&auto=format&fit=crop" },
        price: 12000,
        deposit: 12000,
        location: "Koramangala",
        city: "Bangalore",
        country: "India",
        propertyType: "PG",
        bhk: "1 BHK",
        furnishing: "Fully Furnished",
        status: "approved",
        amenities: ["Security"]
    },
    {
        title: "Emerald Heights",
        description: "Green surroundings and spacious balconies.",
        image: { url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1000&auto=format&fit=crop" },
        price: 35000,
        deposit: 70000,
        location: "Whitefield",
        city: "Bangalore",
        country: "India",
        propertyType: "Flat",
        bhk: "2 BHK",
        furnishing: "Semi-Furnished",
        status: "approved",
        amenities: ["Playground", "Gym"]
    },
    {
        title: "Urban Independent House",
        description: "Stand-alone house with complete privacy.",
        image: { url: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?q=80&w=1000&auto=format&fit=crop" },
        price: 60000,
        deposit: 120000,
        location: "Indiranagar",
        city: "Bangalore",
        country: "India",
        propertyType: "Independent House",
        bhk: "3 BHK",
        furnishing: "Unfurnished",
        status: "approved",
        amenities: ["Power Backup"]
    },
    {
        title: "Sunset Terrace Flat",
        description: "Penthouse style flat with a massive terrace.",
        image: { url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1000&auto=format&fit=crop" },
        price: 85000,
        deposit: 170000,
        location: "Bandra",
        city: "Mumbai",
        country: "India",
        propertyType: "Flat",
        bhk: "3 BHK",
        furnishing: "Fully Furnished",
        status: "approved",
        amenities: ["Security", "Club House"]
    },
    {
        title: "Minimalist PG",
        description: "Clean, modern, and close to the IT Hub.",
        image: { url: "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?q=80&w=1000&auto=format&fit=crop" },
        price: 15000,
        deposit: 15000,
        location: "Hitech City",
        city: "Hyderabad",
        country: "India",
        propertyType: "PG",
        bhk: "1 BHK",
        furnishing: "Fully Furnished",
        status: "approved",
        amenities: ["Power Backup"]
    },
    {
        title: "Riverside Villa",
        description: "Quiet area away from the city noise.",
        image: { url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=1000&auto=format&fit=crop" },
        price: 110000,
        deposit: 300000,
        location: "Gomti Nagar",
        city: "Lucknow",
        country: "India",
        propertyType: "Villa",
        bhk: "4 BHK",
        furnishing: "Semi-Furnished",
        status: "approved",
        amenities: ["Swimming Pool", "Gym"]
    },

    {
        title: "Brick-Stone House",
        description: "Vintage look with modern internal fittings.",
        image: { url: "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?q=80&w=1000&auto=format&fit=crop" },
        price: 40000,
        deposit: 80000,
        location: "Salt Lake",
        city: "Kolkata",
        country: "India",
        propertyType: "Independent House",
        bhk: "2 BHK",
        furnishing: "Unfurnished",
        status: "approved",
        amenities: ["Power Backup"]
    },
    {
        title: "Azure Residences",
        description: "Smart homes with automated lighting.",
        image: { url: "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?q=80&w=1000&auto=format&fit=crop" },
        price: 55000,
        deposit: 110000,
        location: "Sector 150",
        city: "Noida",
        country: "India",
        propertyType: "Flat",
        bhk: "3 BHK",
        furnishing: "Semi-Furnished",
        status: "approved",
        amenities: ["Club House", "Gym"]
    },
    {
        title: "Bachelor's Pad",
        description: "Small but functional apartment in the heart of the city.",
        image: { url: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=1000&auto=format&fit=crop" },
        price: 18000,
        deposit: 30000,
        location: "Pimpri",
        city: "Pune",
        country: "India",
        propertyType: "Flat",
        bhk: "1 BHK",
        furnishing: "Semi-Furnished",
        status: "approved",
        amenities: ["Security"]
    },
    {
        title: "Grand Royal Villa",
        description: "Opulent mansion for a large family.",
        image: { url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop" },
        price: 300000,
        deposit: 1000000,
        location: "Jubilee Hills",
        city: "Hyderabad",
        country: "India",
        propertyType: "Villa",
        bhk: "4 BHK",
        furnishing: "Fully Furnished",
        status: "approved",
        amenities: ["Gym", "Swimming Pool", "Club House"]
    },

    {
        title: "Rustic Farmhouse",
        description: "Peaceful getaway within city limits.",
        image: { url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1000&auto=format&fit=crop" },
        price: 50000,
        deposit: 100000,
        location: "Mehrauli",
        city: "Delhi",
        country: "India",
        propertyType: "Independent House",
        bhk: "4 BHK",
        furnishing: "Unfurnished",
        status: "approved",
        amenities: ["Playground"]
    },
    {
        title: "Modern 1BHK Flat",
        description: "Compact and stylish for young couples.",
        image: { url: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=1000&auto=format&fit=crop" },
        price: 22000,
        deposit: 40000,
        location: "Gachibowli",
        city: "Hyderabad",
        country: "India",
        propertyType: "Flat",
        bhk: "1 BHK",
        furnishing: "Semi-Furnished",
        status: "approved",
        amenities: ["Security"]
    },
    {
        title: "Colonial Bungalow",
        description: "Historical charm with high ceilings and wooden floors.",
        image: { url: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80&w=1000&auto=format&fit=crop" },
        price: 120000,
        deposit: 400000,
        location: "Cantonment",
        city: "Lucknow",
        country: "India",
        propertyType: "Villa",
        bhk: "4 BHK",
        furnishing: "Semi-Furnished",
        status: "approved",
        amenities: ["Power Backup", "Security"]
    },
    {
        title: "City Center PG",
        description: "Best location for office goers.",
        image: { url: "https://images.unsplash.com/photo-1554995207-c18c203602cb?q=80&w=1000&auto=format&fit=crop" },
        price: 14000,
        deposit: 14000,
        location: "T. Nagar",
        city: "Chennai",
        country: "India",
        propertyType: "PG",
        bhk: "1 BHK",
        furnishing: "Fully Furnished",
        status: "approved",
        amenities: ["Power Backup"]
    },

    {
        title: "Skyview 2BHK",
        description: "Above the 20th floor with breathtaking views.",
        image: { url: "https://images.unsplash.com/photo-1484154218962-a197022b5858?q=80&w=1000&auto=format&fit=crop" },
        price: 42000,
        deposit: 85000,
        location: "Worli",
        city: "Mumbai",
        country: "India",
        propertyType: "Flat",
        bhk: "2 BHK",
        furnishing: "Semi-Furnished",
        status: "approved",
        amenities: ["Club House", "Security"]
    },
 
    {
        title: "Executive PG for Women",
        description: "High security and healthy meals provided.",
        image: { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=1000&auto=format&fit=crop" },
        price: 16000,
        deposit: 16000,
        location: "Viman Nagar",
        city: "Pune",
        country: "India",
        propertyType: "PG",
        bhk: "1 BHK",
        furnishing: "Fully Furnished",
        status: "approved",
        amenities: ["Security", "Power Backup"]
    },
    {
        title: "Coastal Breeze Apartment",
        description: "Sea facing flat with constant breeze.",
        image: { url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?q=80&w=1000&auto=format&fit=crop" },
        price: 65000,
        deposit: 150000,
        location: "Besant Nagar",
        city: "Chennai",
        country: "India",
        propertyType: "Flat",
        bhk: "3 BHK",
        furnishing: "Unfurnished",
        status: "approved",
        amenities: ["Security"]
    },

    {
        title: "Charming Attic Flat",
        description: "Cozy space with slanted roofs and roof windows.",
        image: { url: "https://images.unsplash.com/photo-1556020685-ae41abfc9365?q=80&w=1000&auto=format&fit=crop" },
        price: 28000,
        deposit: 50000,
        location: "Malleshwaram",
        city: "Bangalore",
        country: "India",
        propertyType: "Flat",
        bhk: "2 BHK",
        furnishing: "Fully Furnished",
        status: "approved",
        amenities: ["Security"]
    },
    {
        title: "Spacious Duplex",
        description: "Two floors of luxury connected with a spiral staircase.",
        image: { url: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?q=80&w=1000&auto=format&fit=crop" },
        price: 75000,
        deposit: 150000,
        location: "Sector 15",
        city: "Chandigarh",
        country: "India",
        propertyType: "Independent House",
        bhk: "3 BHK",
        furnishing: "Semi-Furnished",
        status: "approved",
        amenities: ["Power Backup", "Playground"]
    },
    {
        title: "Budget 2BHK",
        description: "Clean and practical for a small family.",
        image: { url: "https://images.unsplash.com/photo-1480074568708-e7b720bb3f09?q=80&w=1000&auto=format&fit=crop" },
        price: 18000,
        deposit: 36000,
        location: "Rohini",
        city: "Delhi",
        country: "India",
        propertyType: "Flat",
        bhk: "2 BHK",
        furnishing: "Unfurnished",
        status: "approved",
        amenities: ["Security"]
    },
    {
        title: "Artist's Retreat Villa",
        description: "Inspiring surroundings with plenty of natural light.",
        image: { url: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?q=80&w=1000&auto=format&fit=crop" },
        price: 140000,
        deposit: 400000,
        location: "Palolem",
        city: "Goa",
        country: "India",
        propertyType: "Villa",
        bhk: "3 BHK",
        furnishing: "Fully Furnished",
        status: "approved",
        amenities: ["Swimming Pool", "Power Backup"]
    },
    {
        title: "Corporate PG",
        description: "Tailored for IT professionals with high-speed internet.",
        image: { url: "https://images.unsplash.com/photo-1554995207-c18c203602cb?q=80&w=1000&auto=format&fit=crop" },
        price: 20000,
        deposit: 20000,
        location: "Magarpatta City",
        city: "Pune",
        country: "India",
        propertyType: "PG",
        bhk: "1 BHK",
        furnishing: "Fully Furnished",
        status: "approved",
        amenities: ["Gym", "Security"]
    },
    
];

module.exports = { data: sampleProperties };